imports:
    - { resource: "@SibilleEcommerceBundle/Resources/config/override.yml" }

doctrine:
    dbal:
        connections:
            fre_repository_connection:
                driver: pdo_mysql
                host: localhost
                user: usr_ez
                password: tuCEHafAmXFEzf6T
                dbname: ez
                charset: UTF8
ezpublish:
    imagemagick:
        enabled: true
        path: /usr/bin/convert
    repositories:
        fre_repository:
            engine: legacy
            connection: fre_repository_connection
    siteaccess:
        default_siteaccess: fre
        list:
            - ezdemo_site_clean_user
            - fre
            - ezdemo_site_clean_admin
        groups:
            ezdemo_site_clean_group:
                - ezdemo_site_clean_user
                - fre
                - ezdemo_site_clean_admin
        match:
            Map\Host:
                admin.damien-sibille.fr: ezdemo_site_clean_admin
                www.damien-sibille.fr: ezdemo_site_clean_user
                fre.1: fre
    system:
        ezdemo_site_clean_group:
            repository: fre_repository
            languages:
                - fre-FR
            var_dir: var/ezdemo_site
        fre:
            session:
                name: eZSESSID
        ezdemo_site_clean_admin:
            legacy_mode: true
        ezdemo_site_clean_user:
            session:
                name: eZSESSID
stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false