parameters: 
    ezpublish_legacy.default.view_default_layout: 'SibilleEcommerceBundle::pagelayout.html.twig'
    secret: e19650d5e3f7402976cd11f38d19f7d162c50445
    locale_fallback: en
    mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_user: sibille.damien@gmail.com
    mailer_password: rjqvniwrpiosbqme
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true 
    email_from: sibille_damien@yahoo.fr
    email_to: sibille_damien@yahoo.fr
