#This ezpublish.system preamble states the context these rules apply in
ezpublish:
    system:
        # The siteaccess
        ezdemo_site_clean_user:
            field_templates:
                - { template: SibilleEcommerceBundle::content_fields.html.twig, priority: 10}
            location_view:
                # Type of the view. 'full' is when an object represents the whole page
                full:
                    homepage:
                        controller: SibilleEcommerceBundle:Default:index
                        template: SibilleEcommerceBundle:Default:index.html.twig
                        match:
                            Identifier\ContentType: homepage
                    services:
                        controller: SibilleEcommerceBundle:Service:index
                        template: SibilleEcommerceBundle:full:services.html.twig
                        match:
                            Id\Location: 72
                    profil:
                        controller: SibilleEcommerceBundle:Profil:index
                        template: SibilleEcommerceBundle:full:profil.html.twig
                        match:
                            Id\Location: 123
                    portfolio:
                        controller: SibilleEcommerceBundle:Portfolio:index
                        template: SibilleEcommerceBundle:full:portfolio.html.twig
                        match:
                            Id\Location: 73
                    blog:
                        controller: SibilleEcommerceBundle:Blog:index
                        template: SibilleEcommerceBundle:full:blog.html.twig
                        match:
                            Id\Location: 62
                    projet:
                        controller: SibilleEcommerceBundle:Portfolio:viewLocation
                        template: SibilleEcommerceBundle:full:projet.html.twig
                        match:
                            Identifier\ContentType: projet
                    article:
                        controller: SibilleEcommerceBundle:Blog:viewLocation
                        template: SibilleEcommerceBundle:full:article.html.twig
                        match:
                            Identifier\ContentType: article
                    contact:
                        #controller: SibilleEcommerceBundle:Blog:viewLocation
                        template: SibilleEcommerceBundle:full:contact.html.twig
                        match:
                            Identifier\ContentType: contact
                line:
                    service:
                        template: SibilleEcommerceBundle:line:service.html.twig
                        match:
                            Identifier\ContentType: service
                    projet:
                        template: SibilleEcommerceBundle:line:projet.html.twig
                        match:
                            Identifier\ContentType: projet
                    article:
                        template: SibilleEcommerceBundle:line:article.html.twig
                        match:
                            Identifier\ContentType: article
                    experience:
                        template: SibilleEcommerceBundle:line:experience.html.twig
                        match:
                            Identifier\ContentType: experience
 