parameters:
    email.class: Sibille\EcommerceBundle\Service\Email
services:
    email:
        class:     "%email.class%"
        arguments:
            - "@service_container"
    twig.extension.text:
           class: Twig_Extensions_Extension_Text
           tags:
               - { name: twig.extension }            